# -*- coding: utf-8 -*-
"""Evidence-Aware KAG Solver Extension Package."""

from .models import (
    Claim,
    ClaimStatus,
    ConflictResolutionBasis,
    ConflictStatus,
    EntailmentRelation,
    EvaluatorDecision,
    EvaluatorOutput,
    EvaluatorStatus,
    Evidence,
    EvidenceConflict,
    EvidenceRequirement,
    FourStageEvidenceVerifier,
    IncompleteAnswerResult,
    ModalityType,
    PresenceStatus,
    Provenance,
    ProvenanceValidationStatus,
    RequirementStatus,
    RetrievalStatus,
    SchemaValidationError,
    SemanticProposal,
    Stage1PresenceReceipt,
    Stage2ProvenanceReceipt,
    Stage3EntailmentReceipt,
    Stage4VerificationReceipt,
    StateTransitionReceipt,
    StructuredEvidenceState,
)
from .planner_adapter import EvidenceAwarePlannerAdapter
from .pipeline import KAGEvidenceAwareIterativePipeline

__all__ = [
    "Claim",
    "ClaimStatus",
    "ConflictResolutionBasis",
    "ConflictStatus",
    "EntailmentRelation",
    "EvaluatorDecision",
    "EvaluatorOutput",
    "EvaluatorStatus",
    "Evidence",
    "EvidenceConflict",
    "EvidenceRequirement",
    "FourStageEvidenceVerifier",
    "IncompleteAnswerResult",
    "ModalityType",
    "PresenceStatus",
    "Provenance",
    "ProvenanceValidationStatus",
    "RequirementStatus",
    "RetrievalStatus",
    "SchemaValidationError",
    "SemanticProposal",
    "Stage1PresenceReceipt",
    "Stage2ProvenanceReceipt",
    "Stage3EntailmentReceipt",
    "Stage4VerificationReceipt",
    "StateTransitionReceipt",
    "StructuredEvidenceState",
    "EvidenceAwarePlannerAdapter",
    "KAGEvidenceAwareIterativePipeline",
]
